### ISSUE TITLE
What's the license of the project?

### ISSUE THREAD

**Issue by samueloph** [tdunlap607/docker_vs_cg#1]
Hello,

Would it be possible to update the project to set a license to it, please?

I'm not sure if this is something I can fork/modify/use/send patches as it is right now.

**Comment by tdunlap607** [comment]
Hey @samueloph, sure I've added an Apache 2.0 license. Please let me know if you have any questions or concerns.

**Comment by samueloph** [comment]
Awesome, thank you!
